### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by pistolparody** [conradludgate/neural-rs#1]
Cargo does not build the project , I tried to run the examples too , but no help

```
 --- stderr
  thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', /home/yolo/.cargo/registry/src/github.com-1ecc6299db9ec823/hdf5-sys-0.8.1/build.rs:548:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by conradludgate** [comment]
Ah, I probably left in the line that resumes from checkpoint

**Comment by conradludgate** [comment]
Yeah, there's the line in mnist/main.rs that opens the hdf5 file. Just below it is a commented out `let graph =...`. If you comment/uncomment those respectively it should run.

What error did you get on build?

**Comment by pistolparody** [comment]
> Yeah, there's the line in mnist/main.rs that opens the hdf5 file. Just below it is a commented out `let graph =...`. If you comment/uncomment those respectively it should run.
> 
> What error did you get on build?

Nope didn't help, That's the log from when the error starts butaway
```
  Compiling hdf5-derive v0.8.1
   Compiling hdf5-sys v0.8.1
error: failed to run custom build command for `hdf5-sys v0.8.1`

Caused by:
  process didn't exit successfully: `/home/yolo/Workstation/Clones/neural-rs/target/debug/build/hdf5-sys-19ec8c8eb5260970/build-script-build` (exit status: 101)
  --- stdout
  Attempting to find HDF5 via pkg-config...
  cargo:rerun-if-env-changed=HDF5_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=HDF5_STATIC
  cargo:rerun-if-env-changed=HDF5_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', /home/yolo/.cargo/registry/src/github.com-1ecc6299db9ec823/hdf5-sys-0.8.1/build.rs:548:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by conradludgate** [comment]
Oh right, you need some hdf5 system lib installed or something 😩

**Comment by pistolparody** [comment]
Do you know how can I install them?
